# Localization Dictionary for Financial-Gemi Pro

TRANSLATIONS = {
    "English": {
        "welcome": "Welcome to Financial-Gemi Pro",
        "slogan": "The Antigravity Engine for your Portfolio.",
        "desc_1": "🚀 **AI-Powered Analysis:** Detects hidden patterns and market regimes.",
        "desc_2": "🐋 **Whale Radar:** Tracks smart money and volume anomalies.",
        "desc_3": "🛡️ **Crisis Shield:** Automatic hedge recommendations.",
        "enter_btn": "Enter Simulation",
        "lang_select": "Select Language",
        "sidebar_title": "F-G Pro",
        "region": "Region",
        "sector": "Sector",
        "ticker": "Asset",
        "tab_ai": "🧠 AI Report",
        "tab_news": "📰 News",
        "tab_backtest": "🧪 Backtest",
        "tab_settings": "⚙️ Settings",
        "tab_robo": "🤖 Robo-Advisor",
        "price": "Price",
        "sentiment": "Market Sentiment",
        "whale_alert": "🐋 WHALE ALERT",
        "buy": "BUY",
        "sell": "SELL",
        "hold": "HOLD",
        "advice_header": "Why this decision?",
        "disclaimer": "⚠️ DISCLAIMER: This is an AI model. Not financial advice.",
        "robo_header": "AI Portfolio Manager",
        "robo_budget": "Total Budget",
        "robo_risk": "Risk Profile",
        "robo_gen": "Generate Portfolio",
        "ytd_warning": "⚠️ DISCLAIMER: Not Investment Advice.",
        "update_data_btn": "🔄 Update Data Now",
        "processing": "Processing",
        "completed": "Completed!",
        "system_control": "⚙️ System Control",
        "math_core": "Mathematical Core",
        "active": "Active",
        "core_status_ok": "Status: 100% OPERATIONAL",
        "core_disabled": "Core Disabled",
        "ai_narrator": "AI Narrator",
        "ai_status_online": "Status: ONLINE",
        "ai_sleep": "AI Sleep Mode",
        "sidebar_tip": "💡 **TIP:** Select Region > Sector to access 300+ assets.",
        "whale_radar": "📡 Whale Radar (Live)",
        "whale_caption": "Scans for **abnormal volume** (RVOL > 1.5x) in seconds.",
        "scan_btn": "🔍 Scan Market",
        "scanning": "Scanning...",
        "scan_complete": "Scan Complete!",
        "opps_found": "Opportunities Found!",
        "quick_access": "### 🎯 Quick Access",
        "scan_info": "Press button to scan.",
        "ai_analyzing": "AI Analyzing",
        "error_occurred": "An error occurred",
        "no_data": "No data found or analysis failed.",
        "strong_buy": "Strong Buy Wave!",
        "panic_sell": "Panic Sell Wave!",
        "market_optimistic": "Market Very Optimistic (Hype)",
        "market_fear": "⚠️ Market Fear High (FUD)",
        "crisis_shield": "🛡️ Crisis Shield",
        "shield_desc": "📉 If {0} drops, historically **{1}** tends to rise (Corr: {2}).",
        "shield_inspect": "🛡️ Inspect Shield ({0})",
        "no_hedge": "🛡️ No significant hedge found for this asset.",
        "ai_decision": "AI Decision",
        "chart_price": "Price & Trend",
        "chart_vol": "Volume",
        "chart_rsi": "Momentum (RSI)",
        "chart_macd": "Trend (MACD)",
        "reason_header": "Why This Decision?",
        "logic_header": "AI Logic Report",
        "strategy_note": "Strategy Note",
        "strategy_desc": "This system analyzes **Price Patterns** and **Market Regime** (Volatility).",
        "market_pulse": "📰 Market Pulse & Social",
        "daily_gainers": "### 📈 Daily Gainers",
        "daily_losers": "### 📉 Daily Losers",
        "in_the_news": "In the News {0} (Live)",
        "news_source": "Source: RSS | Date: {0}",
        "read_more": "[Read More]({0})",
        "no_news": "No recent RSS news found for this asset.",
        "sim_mode": "⚠️ *Live data unavailable, simulation mode:*",
        "backtest_header": "Confidence Test (Time Machine)",
        "backtest_desc": "How much would we have earned if we used this strategy **in the past**?",
        "ai_sensitivity": "AI Sensitivity",
        "buy_threshold": "Buy Threshold (Score > X)",
        "threshold_help": "0-30: Aggressive, 50: Balanced, 70-100: Selective.",
        "threshold_info": "ℹ️ **Buy Threshold:** Determines how selective the AI is. High values (70+) buy only on *very strong* signals.",
        "risk_mgmt": "Risk Management",
        "stop_loss": "Stop Loss (%)",
        "stop_loss_help": "Max loss % before selling?",
        "stop_loss_info": "ℹ️ **Stop Loss:** Max tolerance per trade. Auto-sell simulated if drops this much.",
        "start_sim": "▶️ Start Simulation",
        "processing_history": "AI Processing Historical Data...",
        "total_return": "Total Return",
        "max_drawdown": "Max Drawdown",
        "final_balance": "Final Balance",
        "trade_count": "Trade Count",
        "portfolio_curve": "### 📈 Portfolio Curve",
        "curve_desc": "Up is good (profit), down is bad (loss).",
        "trade_log": "📜 Trade Log",
        "settings_header": "🔔 Notification Settings (Telegram)",
        "settings_desc": "Get BUY/SELL signals to your phone.",
        "save_settings": "💾 Save Settings",
        "test_msg": "📨 Send Test Message",
        "robo_desc": "Calculates efficient portfolio allocation based on risk.",
        "preferences": "👇 Set Preferences",
        "robo_caption": "Suggests a forward-looking basket (Not backtest).",
        "risk_conservative": "Conservative (Low Risk)",
        "risk_balanced": "Balanced (Medium)",
        "risk_aggressive": "Aggressive (High Return)",
        "sector_focus": "Sector Focus (Optional)",
        "all_sectors": "All (Leave Empty)",
        "creating_portfolio": "AI scanning market and creating basket...",
        "rec_allocation": "Recommended Allocation",
        "buy_list": "### 📋 Buy List",
        "start_prompt": "👈 Select budget and risk to start.",
        "legal_warning": "⚠️ **LEGAL WARNING:** These are statistical AI models. Not investment advice.",
        # --- NARRATIVE ENGINE ---
        "report_title": "📊 {0} Deep Dive Analysis Report",
        "decision_label": "**Decision:** {0} | **Trend:** {1}",
        "decision_neutral": "NEUTRAL",
        "decision_pos": "POSITIVE",
        "decision_neg": "NEGATIVE",
        "strategic_logic_header": "### 1. Strategic Logic (Why?)",
        "trend_analysis_up": "- **Trend Analysis:** Price is above SMA 50, indicating a medium-term UPTREND.",
        "trend_analysis_down": "- **Trend Analysis:** Price is below SMA 50, bears are dominant.",
        "vol_support": "- **Volume Support:** Daily volume factor **{0:.2f}x**. ",
        "vol_strong": "High volume indicates institutional participation.",
        "vol_weak": "Volume is weak, the move is not convincing.",
        "ai_sentiment_header": "### 2. AI Market Sentiment",
        "sent_label_pos": "Positive (Bullish)",
        "sent_label_neg": "Negative (Bearish)",
        "sent_label_neutral": "Neutral",
        "global_news_score": "- **Global News Score:** `{0:.2f}` ({1})",
        "ai_sent_desc": "- AI scanned global news flow to gauge market psychology. ",
        "ai_sent_bull": "News is encouraging buyers.",
        "ai_sent_bear": "News is creating pressure.",
        "risk_header": "### 3. Risk & Volatility",
        "risk_desc": "- **Volatility:** The system automatically adjusts position size based on market regime.",
        "risk_advice": "- **Advice:** If opening a position, risk only a small portion of capital.",
        "footer_advice": "Trend is {0} and AI Sentiment is {1}. ",
        "advice_buy": "Buying opportunities can be sought.",
        "advice_hold": "Caution advised, staying in cash is safer.",
        # --- RAG AGENT ---
        "ai_news_summary_header": "\n\n**📰 AI News Summary:**\n",
        "rag_summary": "Scanned {0} real-time sources. Sentiment is {1}.",
        "rag_pos": "POSITIVE",
        "rag_neg": "NEGATIVE",
        "rag_neutral": "NEUTRAL",
        "rag_no_data": "No news data available for sentiment analysis.",
        "rag_bull": "🟢 BULL",
        "rag_bear": "🔴 BEAR",
        "rag_neutr": "⚪ NEUTR"
    },
    "Türkçe": {
        "welcome": "VisionFinance-Pro'ya Hoşgeldiniz",
        "slogan": "Portföyünüz için Profesyonel Analiz.",
        "desc_1": "🚀 **Yapay Zeka Analizi:** Gizli formasyonları ve piyasa rejimlerini tespit eder.",
        "desc_2": "🐋 **Balina Radarı:** Akıllı parayı ve hacim anormalliklerini izler.",
        "desc_3": "🛡️ **Kriz Kalkanı:** Otomatik hedge (korunma) önerileri sunar.",
        "enter_btn": "Simülasyona Gir",
        "lang_select": "Dil Seçimi",
        "sidebar_title": "F-G Pro",
        "region": "Bölge",
        "sector": "Sektör",
        "ticker": "Varlık",
        "tab_ai": "🧠 AI Raporu",
        "tab_news": "📰 Haberler",
        "tab_backtest": "🧪 Backtest",
        "tab_settings": "⚙️ Ayarlar",
        "tab_robo": "🤖 AI Portföy",
        "price": "Fiyat",
        "sentiment": "Piyasa Duygusu",
        "whale_alert": "🐋 BALİNA ALARMI",
        "buy": "AL",
        "sell": "SAT",
        "hold": "TUT",
        "advice_header": "Neden Bu Karar?",
        "disclaimer": "⚠️ YASAL UYARI: Bu bir AI modelidir. Yatırım tavsiyesi değildir.",
        "robo_header": "Yapay Zeka Portföy Yöneticisi",
        "robo_budget": "Toplam Bütçe",
        "robo_risk": "Risk Profili",
        "robo_gen": "Portföyü Oluştur",
        "ytd_warning": "⚠️ **YTD:** Yatırım Tavsiyesi Değildir.",
        "update_data_btn": "🔄 Verileri Şimdi Güncelle",
        "processing": "İşleniyor",
        "completed": "Tamamlandı!",
        "system_control": "⚙️ Sistem Kontrolü",
        "math_core": "Matematiksel Çekirdek",
        "active": "Aktif",
        "core_status_ok": "Durum: %100 OPERASYONEL",
        "core_disabled": "Çekirdek Devre Dışı",
        "ai_narrator": "Yapay Zeka (AI)",
        "ai_status_online": "Durum: ONLINE",
        "ai_sleep": "AI Uyku Modunda",
        "sidebar_tip": "💡 **İPUCU:** Sol üstten Bölge > Sektör seçerek 300+ varlığa erişebilirsiniz.",
        "whale_radar": "📡 Balina Radarı (Canlı)",
        "whale_caption": "Piyasadaki **anormal hacim** hareketlerini (RVOL > 1.5x) saniyeler içinde tarar ve listeler.",
        "scan_btn": "🔍 Piyasayı Tara",
        "scanning": "Taranıyor...",
        "scan_complete": "Tarama Tamamlandı!",
        "opps_found": "Fırsat Bulundu!",
        "quick_access": "### 🎯 Hızlı Erişim",
        "scan_info": "Tarama yapmak için butona basın.",
        "ai_analyzing": "AI Analiz Ediyor",
        "error_occurred": "Bir hata oluştu",
        "no_data": "Veri bulunamadı veya analiz yapılamadı.",
        "strong_buy": "Güçlü Alım Dalgası!",
        "panic_sell": "Panik Satış Dalgası!",
        "market_optimistic": "Piyasa Çok İyimser (Hype Var)",
        "market_fear": "⚠️ Piyasa Risk Algısı Yüksek (FUD)",
        "crisis_shield": "🛡️ Kriz Kalkanı",
        "shield_desc": "📉 Eğer {0} düşerse, tarihsel olarak **{1}** yükselme eğilimindedir (Korelasyon: {2}).",
        "shield_inspect": "🛡️ Kalkanı İncele ({0})",
        "no_hedge": "🛡️ Bu varlık için belirgin bir ters korelasyon (hedge) bulunamadı.",
        "ai_decision": "AI Kararı",
        "chart_price": "Fiyat & Trend",
        "chart_vol": "Hacim",
        "chart_rsi": "Momentum (RSI)",
        "chart_macd": "Trend (MACD)",
        "reason_header": "Neden Bu Karar?",
        "logic_header": "Kafa Raporu (Mantık Akışı)",
        "strategy_note": "Strateji Notu",
        "strategy_desc": "Bu sistem **Fiyat Formasyonları** ve **Piyasa Rejimi** (Volatilite) analizi yapar.",
        "market_pulse": "📰 Piyasa Bülteni & Sosyal Akış",
        "daily_gainers": "### 📈 Günün Kazananları",
        "daily_losers": "### 📉 Günün Kaybedenleri",
        "in_the_news": "Basında {0} (Canlı)",
        "news_source": "Kaynak: RSS | Tarih: {0}",
        "read_more": "[Haberin Devamı İçin Tıkla]({0})",
        "no_news": "Bu varlık için güncel RSS haberi bulunamadı (veya genel piyasa haberi gösteriliyor).",
        "sim_mode": "⚠️ *Canlı veri çekilemedi, simülasyon modu:*",
        "backtest_header": "Güven Testi (Zaman Makinesi)",
        "backtest_desc": "Bu stratejiyi **geçmişte kullansaydık** ne kadar kazanırdık?",
        "ai_sensitivity": "AI Hassasiyeti",
        "buy_threshold": "Alım Eşiği (Skor > X)",
        "threshold_help": "0-30: Agresif, 50: Dengeli, 70-100: Seçici.",
        "threshold_info": "ℹ️ **Alım Eşiği:** AI'nın ne kadar seçici olacağını belirler. Yüksek değerler (70+) sadece *çok güçlü* sinyallerde alım yapar.",
        "risk_mgmt": "Risk Yönetimi",
        "stop_loss": "Stop Loss (%)",
        "stop_loss_help": "Fiyat % kaç düşerse zararı kesip satalım?",
        "stop_loss_info": "ℹ️ **Stop Loss:** Bir işlemde kabul edilen maksimum zarar oranıdır. Fiyat bu kadar düşerse otomatik satış simüle edilir.",
        "start_sim": "▶️ Simülasyonu Başlat",
        "processing_history": "AI Geçmiş Veriyi İşliyor...",
        "total_return": "Toplam Getiri",
        "max_drawdown": "Max Drawdown",
        "final_balance": "Son Bakiye",
        "trade_count": "İşlem Sayısı",
        "portfolio_curve": "### 📈 Portföy Gelişimi (Equity Curve)",
        "curve_desc": "Eğri yukarı gidiyorsa para kazanıyoruz, aşağı gidiyorsa strateji zarar yazıyor demektir.",
        "trade_log": "📜 İşlem Kayıtları (Trade Log)",
        "settings_header": "🔔 Bildirim Ayarları (Telegram)",
        "settings_desc": "Bilgisayar başında değilken bile 'AL/SAT' sinyalleri cebinize gelsin.",
        "save_settings": "💾 Ayarları Kaydet",
        "test_msg": "📨 Test Mesajı Gönder",
        "robo_desc": "Paranızı risk profilinize göre **en verimli** nasıl bölebileceğinizi hesaplar.",
        "preferences": "👇 Tercihlerinizi Ayarlayın",
        "robo_caption": "Bu modül, geleceğe yönelik optimal bir portföy sepeti önerir (Backtest değildir).",
        "risk_conservative": "Muhafazakar (Düşük Risk)",
        "risk_balanced": "Dengeli (Orta)",
        "risk_aggressive": "Agresif (Yüksek Getiri)",
        "sector_focus": "Sektör Odaklanması (Opsiyonel)",
        "all_sectors": "Tümü (Boş Bırakın)",
        "creating_portfolio": "AI piyasayı tarıyor ve optimal sepeti hazırlıyor...",
        "rec_allocation": "Önerilen Dağılım",
        "buy_list": "### 📋 Alım Listesi",
        "start_prompt": "👈 Başlamak için sol taraftan bütçe ve risk seçin, sonra butona basın.",
        "legal_warning": "⚠️ **YASAL UYARI:** Bu sonuçlar yapay zeka tarafından geçmiş verilere dayalı üretilen istatistiksel bir modeldir. Kesinlikle yatırım tavsiyesi değildir. Son karar her zaman size aittir.",
        # --- NARRATIVE ENGINE ---
        "report_title": "📊 {0} Derinlemesine Analiz Raporu",
        "decision_label": "**Karar:** {0} | **Trend:** {1}",
        "decision_neutral": "NÖTR",
        "decision_pos": "POZİTİF",
        "decision_neg": "NEGATİF",
        "strategic_logic_header": "### 1. Stratejik Mantık (Neden?)",
        "trend_analysis_up": "- **Trend Analizi:** Fiyat 50 günlük ortalamanın üzerinde, bu da orta vadeli bir yükseliş trendine işaret ediyor.",
        "trend_analysis_down": "- **Trend Analizi:** Fiyat 50 günlük ortalamanın altında, ayılar (satıcılar) piyasaya hakim.",
        "vol_support": "- **Hacim Desteği:** Günlük hacim katsayısı **{0:.2f}x**. ",
        "vol_strong": "Hacimli bir hareket, kurumsal giriş/çıkış olduğunu gösterir.",
        "vol_weak": "Hacim zayıf, hareket güven vermiyor.",
        "ai_sentiment_header": "### 2. AI Piyasa Algısı (Sentiment)",
        "sent_label_pos": "Pozitif (Boğa)",
        "sent_label_neg": "Negatif (Ayı)",
        "sent_label_neutral": "Nötr",
        "global_news_score": "- **Global Haber Puanı:** `{0:.2f}` ({1})",
        "ai_sent_desc": "- AI, küresel haber akışını tarayarak piyasa oyuncularının psikolojisini ölçtü. ",
        "ai_sent_bull": "Haberler alıcıları cesaretlendiriyor.",
        "ai_sent_bear": "Haberler baskı yaratıyor.",
        "risk_header": "### 3. Risk ve Volatilite",
        "risk_desc": "- **Oynaklık (Volatilite):** Piyasa rejimi değişimlerine karşı sistem otomatik olarak pozisyon büyüklüğünü ayarlar.",
        "risk_advice": "- **Tavsiye:** Eğer pozisyon açacaksanız, sermayenizin küçük bir kısmını riske etmelisiniz.",
        "footer_advice": "Trend {0} ve AI Sentiment {1}. ",
        "advice_buy": "Alım fırsatları kovalanabilir.",
        "advice_hold": "Temkinli olunmalı, nakitte kalmak daha güvenli.",
        # --- RAG AGENT ---
        "ai_news_summary_header": "\n\n**📰 AI Haber Özeti:**\n",
        "rag_summary": "{0} gerçek zamanlı kaynak tarandı. Sentiment: {1}.",
        "rag_pos": "POZİTİF",
        "rag_neg": "NEGATİF",
        "rag_neutral": "NÖTR",
        "rag_no_data": "Sentiment analizi için veri bulunamadı.",
        "rag_bull": "🟢 BOĞA",
        "rag_bear": "🔴 AYI",
        "rag_neutr": "⚪ NÖTR"
    },
    }

def get_text(key, lang="Türkçe"):
    """
    Retrieves translation for a key. Defaults to English if key/lang missing.
    """
    # Debugging
    # print(f"DEBUG: get_text key={key} lang={lang}")
    
    # Default fallback chain: Requested Lang -> English -> Key itself
    lang_dict = TRANSLATIONS.get(lang, TRANSLATIONS["English"])
    
    # Try getting key from specific lang
    res = lang_dict.get(key)
    
    # If missing, try English
    if not res:
        # print(f"DEBUG: Missing {key} in {lang}, falling back to English")
        res = TRANSLATIONS["English"].get(key, key)
        
    return res

def get_available_languages():
    return list(TRANSLATIONS.keys())
