import pandas as pd
import pandas_ta as ta
import numpy as np

def add_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Adds technical indicators to the dataframe.
    This is the 'Feature Engineering' step where we translate raw price
    into meaningful signals for the AI.
    
    Args:
        df: DataFrame with columns [Open, High, Low, Close, Volume]
        
    Returns:
        DataFrame with added feature columns.
    """
    if df.empty:
        return df
        
    # Copy to avoid SettingWithCopy warnings
    df = df.copy()
    
    # 1. Volatility (Critical for Risk Layer)
    # Calculate log returns
    df['log_ret'] = np.log(df['Close'] / df['Close'].shift(1))
    # Rolling 21-day volatility (approx 1 trading month), annualized
    df['volatility_21'] = df['log_ret'].rolling(window=21).std() * np.sqrt(252)
    
    # 2. Trend Strength (For Regime Detection)
    # ADX > 25 usually indicates a strong trend
    adx_df = ta.adx(df['High'], df['Low'], df['Close'], length=14)
    # pandas_ta returns 3 columns (ADX, DMP, DMN), we just want ADX
    if adx_df is not None and not adx_df.empty:
        df['ADX_14'] = adx_df['ADX_14']
    
    # 3. Momentum (For Entry/Exit Signals)
    df['RSI_14'] = ta.rsi(df['Close'], length=14)
    df['ATR_14'] = ta.atr(df['High'], df['Low'], df['Close'], length=14)
    
    # 4. Long Term Trend Bias
    df['SMA_50'] = ta.sma(df['Close'], length=50)
    df['SMA_200'] = ta.sma(df['Close'], length=200)
    
    # Trend alignment: True if Price > SMA200
    df['trend_long'] = np.where(df['Close'] > df['SMA_200'], 1, -1)
    
    # Drop initial Rows with NaN values generated by indicators (e.g. first 200 days)
    df.dropna(inplace=True)
    
    return df

if __name__ == "__main__":
    # Test with a dummy dataframe or existing file
    import os
    sample_file = os.path.join(os.path.dirname(__file__), "raw", "SPY.parquet")
    
    if os.path.exists(sample_file):
        print(f"Testing features on {sample_file}...")
        df_raw = pd.read_parquet(sample_file)
        df_feat = add_features(df_raw)
        print("Features added successfully:")
        print(df_feat[['Close', 'volatility_21', 'ADX_14', 'RSI_14']].tail())
    else:
        print("No sample data found. Run market_data.py first.")
